name: TaterSync
version: '${version}'
author: p0t4t0sandwich
main: ca.sperrer.p0t4t0sandwich.tatersync.bukkit.BukkitMain
description: A plugin to sync player data across servers
folia-supported: true
